# Generated by Django 5.0.4 on 2024-04-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pic', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url4', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url5', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url6', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url7', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url8', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url9', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url10', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
